# permissions for end users to view clickhouses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clickhouse-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ppo-test
    app.kubernetes.io/part-of: ppo-test
    app.kubernetes.io/managed-by: kustomize
  name: clickhouse-viewer-role
rules:
- apiGroups:
  - connectors.magnit.tech
  resources:
  - clickhouses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - connectors.magnit.tech
  resources:
  - clickhouses/status
  verbs:
  - get
