---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - connectors.magnit.tech
  resources:
  - clickhouses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - connectors.magnit.tech
  resources:
  - clickhouses/finalizers
  verbs:
  - update
- apiGroups:
  - connectors.magnit.tech
  resources:
  - clickhouses/status
  verbs:
  - get
  - patch
  - update
